units:
  px: u + 1
  py: u + 1
points:
  zones:
    matrix:
      anchor:
        shift: [40, -150]
      key:
        spread: 1U
        padding: 1U+1
      columns:
        outer:
          key.column_net: P14
          key.padding: 1cy + 1
        pinky:
          key.stagger: 0.2u
          key.rotate: -1
          key.splay: 2
          key.spread: 1cx + 2
          key.column_net: P16
        ring:
          key.stagger: 0.5u
          key.rotate: -1.5
          key.splay: -10
          key.spread: 1u + 5
          key.column_net: P10
        middle:
          key.stagger: 0.5u
          key.splay: -8
          key.spread: 1u + 4
          key.column_net: P6
        index:
          key.stagger: -0.5u
          key.splay: -8
          key.rotate: -0.5
          key.spread: 1u + 5
          key.column_net: P7
      rows:
        bottom:
          row_net: P18
        home:
          row_net: P19
        top:
          row_net: P20
        num:
          shift: [0, 1cy-1U]
          row_net: P21
    thumbs:
      key:
        splay: -4
        stagger: -1
        padding: cx
      columns:
        layer:
          key.column_net: P9
        space:
          key.column_net: P8
      rows:
        one:
          row_net: P18
        two:
          row_net: P19
      anchor:
        ref: matrix_index_bottom
        shift: [1.5u, -1.5u]
        rotate: 0
  mirror: &mirror
    ref: matrix_index_num
    distance: 5u
outlines:
  mx_keys:
    - what: rectangle
      where: 
        - /^mirror(?!.*num)(?!.*outer)(?!.*thumbs).*$/
        - /^matrix(?!.*num)(?!.*outer)(?!.*thumbs).*$/
      bound: false
      size: 1u
      fillet: 1
  choc_keys:
    - what: rectangle
      where: 
        - /.*(num|outer).*/
        - /thumbs/
      bound: false
      size: [1cx,1cy]
      fillet: 1
  left:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_ring_num
          shift: [-0.75px,0.75py]
        - ref: matrix_middle_num
          shift: [0px,1py]
        - ref: matrix_index_num
          shift: [2.25px,0.75py]
        - ref: thumbs_space_two
          shift: [-0.5px,1.5py]
        - ref: thumbs_space_one
          shift: [-1.65px,2.4py]
        - ref: thumbs_space_one
          shift: [-1.6px, 1.65py]
        - ref: thumbs_space_two
          shift: [0.75px,0.75py]
        - ref: thumbs_space_one
          shift: [0.75px,-0.75py]
        - ref: matrix_pinky_bottom
          shift: [0.75px,-0.75py]
        - ref: matrix_outer_bottom
          shift: [-0.75px,-0.75py]
        - ref: matrix_outer_num
          shift: [-0.75px,0.75py]
  right:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_ring_num
          shift: [-0.75px,0.75py]
        - ref: mirror_matrix_middle_num
          shift: [0px,1py]
        - ref: mirror_matrix_index_num
          shift: [2.25px,0.75py]
        - ref: mirror_thumbs_space_two
          shift: [-0.5px,1.5py]
        - ref: mirror_thumbs_space_one
          shift: [-1.65px,2.4py]
        - ref: mirror_thumbs_space_one
          shift: [-1.6px, 1.65py]
        - ref: mirror_thumbs_space_two
          shift: [0.75px,0.75py]
        - ref: mirror_thumbs_space_one
          shift: [0.75px,-0.75py]
        - ref: mirror_matrix_pinky_bottom
          shift: [0.75px,-0.75py]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.75px,-0.75py]
        - ref: mirror_matrix_outer_num
          shift: [-0.75px,0.75py]
  left_mx:
    - name: left
    - operation: subtract
      name: mx_keys
  left_choc:
    - name: left
    - operation: subtract
      name: choc_keys
  left_full:
    - name: left_mx
    - operation: stack
      name: left_choc
  right_mx:
    - name: right
    - operation: subtract
      name: mx_keys
  right_choc:
    - name: right
    - operation: subtract
      name: choc_keys
  right_full:
    - name: right_mx
    - operation: stack
      name: right_choc
pcbs:
  central:
    template: kicad8
    outlines:
      main:
        outline: left_full
    footprints:
      mx_hotswap:
        what: ceoloide/switch_mx
        where: 
          - matrix_index_bottom
          - matrix_pinky_bottom
          - matrix_ring_bottom
          - matrix_middle_bottom
          - matrix_index_home
          - matrix_pinky_home
          - matrix_ring_home
          - matrix_middle_home
          - matrix_index_top
          - matrix_pinky_top
          - matrix_ring_top
          - matrix_middle_top
        params:
          hotswap: true
          from: "{{column_net}}"
          to: "{{name}}"
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2 
        where: 
          - matrix_index_num
          - matrix_outer_num
          - matrix_pinky_num
          - matrix_ring_num
          - matrix_middle_num
          - matrix_outer_top
          - matrix_outer_home
          - matrix_outer_bottom
          - /^thumbs.*/
        params:
          hotswap: true
          from: "{{column_net}}"
          to: "{{name}}"
        # Controller
      nice_nano:
         what: ceoloide/mcu_nice_nano
         params:
           reverse_mount: true
         where:
           ref: matrix_index_num
           shift: [1.25u, -0.35u]
      nice_view:
        what: ceoloide/display_nice_view
        where:
           ref: matrix_index_num
           shift: [1.75u, -0.6u]
      encoder:
        what: ceoloide/rotary_encoder_ec11_ec12
        where:
           ref: thumbs_space_two
        params:
          mounting_holes_position: 7.5
          include_momentary_switch_pads: true
          include_plate_hole_marking: true
          include_silkscreen: true
          include_plated_mounting_holes: true
          S1: "{{name}}"
          S2: "{{colrow}}"
        adjust:
          rotate: 180
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: matrix_index_num
          shift: [2u, 0.45u]
        params:
            pos: pos
            neg: gnd
      # Reset switch (horizontal community version)
      horizontal_reset:
        what: ceoloide/reset_switch_smd_side
        params: 
          from: GND
          to: RST 
        where:
          ref: matrix_index_num
          shift: [2u, -0.2u]
          rotate: -90.0
      # Battery on/off switch
      battery_switch:
        what: ceoloide/power_switch_smd_side
        where:
            ref: matrix_index_num
            shift: [2u, -0.75u]
        params:
            from: pos
            to: RAW
      diode:
        what: ceoloide/diode_tht_sod123
        where: 
          - /^matrix.*/
          - /^thumbs.*/
        params:
          include_tht: false
          from: "{{name}}"
          to: "{{row}}"
        adjust:
          shift: [0, -5]
  peripheral:
    template: kicad8
    outlines:
      main:
        outline: right_full
    footprints:
      mx_hotswap:
        what: ceoloide/switch_mx
        where: 
          - mirror_matrix_index_bottom
          - mirror_matrix_pinky_bottom
          - mirror_matrix_ring_bottom
          - mirror_matrix_middle_bottom
          - mirror_matrix_index_home
          - mirror_matrix_pinky_home
          - mirror_matrix_ring_home
          - mirror_matrix_middle_home
          - mirror_matrix_index_top
          - mirror_matrix_pinky_top
          - mirror_matrix_ring_top
          - mirror_matrix_middle_top
        params:
          hotswap: true
          from: "{{column_net}}"
          to: "{{name}}"
      holes_bottom:
        what: ceoloide/mounting_hole_plated
        where: /^mirror.*bottom$/
        adjust:
          shift: [0, -0.4u]
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2 
        where: 
          - mirror_matrix_index_num
          - mirror_matrix_outer_num
          - mirror_matrix_pinky_num
          - mirror_matrix_ring_num
          - mirror_matrix_middle_num
          - mirror_matrix_outer_top
          - mirror_matrix_outer_home
          - mirror_matrix_outer_bottom
          - /mirror_thumbs/
        params:
          hotswap: true
          from: "{{column_net}}"
          to: "{{name}}"
      holes_num:
        what: ceoloide/mounting_hole_plated
        where: /^mirror.*num$/
        adjust:
          shift: [0, 0.4u]
      # Controller
      nice_nano:
         what: ceoloide/mcu_nice_nano
         params:
           reverse_mount: true
         where:
           ref: mirror_matrix_index_num
           shift: [1.25u, -0.35u]
      nice_view:
        what: ceoloide/display_nice_view
        where:
           ref: mirror_matrix_index_num
           shift: [1.75u, -0.6u]
      hole_panel:
        what: ceoloide/mounting_hole_plated
        where:
           ref: mirror_matrix_index_num
           shift: [1u, -1.5u]
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: mirror_matrix_index_num
          shift: [2u, 0.45u]
        params:
            pos: pos
            neg: gnd
      # Reset switch (horizontal community version)
      horizontal_reset:
        what: ceoloide/reset_switch_smd_side
        params: 
          from: GND
          to: RST 
        where:
          ref: mirror_matrix_index_num
          shift: [2u, -0.2u]
          rotate: -90.0
      # Battery on/off switch
      battery_switch:
        what: ceoloide/power_switch_smd_side
        where:
            ref: mirror_matrix_index_num
            shift: [2u, -0.75u]
        params:
            from: pos
            to: RAW
      trackpoint:
        what: infused-kim/trackpoint_mount
        where: 
            ref: mirror_thumbs_layer_one
            shift: [0.61u, 0.465u]
        params:  
          show_outline_t430: true
          show_board: true
      diode:
        what: ceoloide/diode_tht_sod123
        where:
          - /^mirror.*/
        params:
          include_tht: false
          from: "{{name}}"
          to: "{{row}}"
        adjust:
          shift: [0, -5]
