units:
  px: u + 1
  py: cy + 1
points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      key:
        spread: 1.5u
        padding: 1u
      columns:
        outer:
          key.column_net: P14
        pinky:
          key.stagger: 0.2u
          key.spread: 1.2u
          key.column_net: P16
        ring:
          key.stagger: 0.8u
          key.splay: -10
          key.column_net: P10
        middle:
          key.stagger: 0.4u
          key.splay: -4
          key.spread: 1.2u
          key.column_net: P6
        index:
          key.stagger: -0.6u
          key.splay: -8
          key.column_net: P7
      rows:
        bottom:
          row_net: P18
        home:
          row_net: P19
        top:
          key:
            padding:0
          row_net: P20
        num:
          row_net: P21
    thumbs:
      key:
        splay: -4
        stagger: -2
        spread: 1.2u
      columns:
        layer:
          key.column_net: P9
        space:
          key.column_net: P8
      rows:
        one:
          row_net: P18
        two:
          row_net: P19
      anchor:
        ref: matrix_index_bottom
        shift: [2u, -0.5u]
        rotate: -1.5u
  mirror: &mirror
    ref: matrix_index_num
    distance: 5u
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [px-0.5,py-0.5]
  left:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_ring_num
          shift: [-0.75px,0.75py]
        - ref: matrix_middle_num
          shift: [0px,1py]
        - ref: matrix_index_num
          shift: [2.25px,0.75py]
        - ref: thumbs_space_one
          shift: [-2px,1.75py]
        - ref: thumbs_space_two
          shift: [0.75px,0.75py]
        - ref: thumbs_space_one
          shift: [0.75px,-0.75py]
        - ref: matrix_index_bottom
          shift: [0.75px,-1py]
        - ref: matrix_pinky_bottom
          shift: [0.75px,-0.75py]
        - ref: matrix_outer_bottom
          shift: [-0.75px,-0.75py]
        - ref: matrix_outer_num
          shift: [-0.75px,0.75py]
      fillet: 3
  right:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_ring_num
          shift: [-0.75px,0.75py]
        - ref: mirror_matrix_middle_num
          shift: [0px,1py]
        - ref: mirror_matrix_index_num
          shift: [2.25px,0.75py]
        - ref: mirror_thumbs_space_one
          shift: [-2px,1.75py]
        - ref: mirror_thumbs_space_two
          shift: [0.75px,0.75py]
        - ref: mirror_thumbs_space_one
          shift: [0.75px,0.5py]
        - ref: mirror_thumbs_space_one
          shift: [0.75px,-0.75py]
        - ref: mirror_matrix_index_bottom
          shift: [0.5px,-1.25py]
        - ref: mirror_matrix_pinky_bottom
          shift: [0.75px,-0.75py]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.75px,-0.75py]
        - ref: mirror_matrix_outer_num
          shift: [-0.75px,0.75py]
      fillet: 3
  combo-left:
    - name: left
    - operation: subtract
      name: keys
  combo-right:
    - name: right
    - operation: subtract
      name: keys
pcbs:
  central:
    template: kicad8
    outlines:
      main:
        outline: left
    footprints:
      mx_hotswap:
        what: ceoloide/switch_mx
        where: 
          - matrix_index_bottom
          - matrix_pinky_bottom
          - matrix_ring_bottom
          - matrix_middle_bottom
          - matrix_index_home
          - matrix_pinky_home
          - matrix_ring_home
          - matrix_middle_home
          - matrix_index_top
          - matrix_pinky_top
          - matrix_ring_top
          - matrix_middle_top

          - thumbs_space_one
          - thumbs_layer_one
          - thumbs_layer_two
        params:
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      mx_hotswap_encoder:
        what: ceoloide/switch_mx
        where: thumbs_space_two
        params:
          hotswap: true
          outer_pad_height: 2.5
          from: "{{column_net}}"
          to: "{{colrow}}"
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2 
        where: 
          - matrix_index_num
          - matrix_outer_num
          - matrix_pinky_num
          - matrix_ring_num
          - matrix_middle_num
          - matrix_outer_top
          - matrix_outer_home
          - matrix_outer_bottom
        params:
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        # Controller
      nice_nano:
         what: ceoloide/mcu_nice_nano
         params:
           reverse_mount: true
         where:
           ref: matrix_index_num
           shift: [1.25u, -0.35u]
      nice_view:
        what: ceoloide/display_nice_view
        where:
           ref: matrix_index_num
           shift: [1.75u, -0.6u]
      encoder:
        what: ceoloide/rotary_encoder_ec11_ec12
        where:
           ref: thumbs_space_two
        params:
          mounting_holes_position: 7.5
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: matrix_index_num
          shift: [2u, 0.45u]
        params:
            side: b
            pos: pos
            neg: gnd
      # Reset switch (horizontal community version)
      horizontal_reset:
        what: ceoloide/reset_switch_smd_side
        params: 
          side: B
          from: GND
          to: RST 
        where:
          ref: matrix_index_num
          shift: [2u, -0.2u]
          rotate: -90.0
      # Battery on/off switch
      battery_switch:
        what: ceoloide/power_switch_smd_side
        where:
            ref: matrix_index_num
            shift: [2u, -0.75u]
        params:
            side: B
            from: pos
            to: RAW
      diode:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
  peripheral:
    template: kicad8
    outlines:
      main:
        outline: right
    footprints:
      mx_hotswap:
        what: ceoloide/switch_mx
        where: 
          - mirror_matrix_index_bottom
          - mirror_matrix_pinky_bottom
          - mirror_matrix_ring_bottom
          - mirror_matrix_middle_bottom
          - mirror_matrix_index_home
          - mirror_matrix_pinky_home
          - mirror_matrix_ring_home
          - mirror_matrix_middle_home
          - mirror_matrix_index_top
          - mirror_matrix_pinky_top
          - mirror_matrix_ring_top
          - mirror_matrix_middle_top

          - mirror_thumbs_space_one
          - mirror_thumbs_space_two
          - mirror_thumbs_layer_one
          - mirror_thumbs_layer_two
        params:
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2 
        where: 
          - mirror_matrix_index_num
          - mirror_matrix_outer_num
          - mirror_matrix_pinky_num
          - mirror_matrix_ring_num
          - mirror_matrix_middle_num
          - mirror_matrix_outer_top
          - mirror_matrix_outer_home
          - mirror_matrix_outer_bottom
        params:
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        # Controller
      nice_nano:
         what: ceoloide/mcu_nice_nano
         params:
           reverse_mount: true
         where:
           ref: mirror_matrix_index_num
           shift: [1.25u, -0.35u]
      nice_view:
        what: ceoloide/display_nice_view
        where:
           ref: mirror_matrix_index_num
           shift: [1.75u, -0.6u]
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: mirror_matrix_index_num
          shift: [2u, 0.45u]
        params:
            pos: pos
            neg: gnd
      # Reset switch (horizontal community version)
      horizontal_reset:
        what: ceoloide/reset_switch_smd_side
        params: 
          from: GND
          to: RST 
        where:
          ref: mirror_matrix_index_num
          shift: [2u, -0.2u]
          rotate: -90.0
      # Battery on/off switch
      battery_switch:
        what: ceoloide/power_switch_smd_side
        where:
            ref: mirror_matrix_index_num
            shift: [2u, -0.75u]
        params:
            side: B
            from: pos
            to: RAW
      trackpoint:
        what: infused-kim/trackpoint_mount
        where: 
            ref: mirror_thumbs_layer_one
            shift: [0.61u, 0.465u]
        params:  
          show_outline_t430: true
          show_board: true
      diode:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
